In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [15]:
df = pd.read_csv('motorcycle-crash-data.csv', low_memory=False)

In [16]:
df.drop(columns='Unnamed: 0', inplace=True)
df

,Crash Record Number,County Code,County Name,Municipality Code,Municipality Name,District Code,District Name,Police Agency Code,Police Agency Name,Crash Year,...,Suspected Serious Injury,Suspected Minor Injury,Possible Injury,Motorcycle Drinking Driver,Drug Related,Illegal Drug Related,School Bus Unit,Drugged Driver,Impaired Driver,Geographic Location of the Crash
0,2016000348,9,Bucks,9218,Northampton Twp,6,District 6-0,09218,NORTHAMPTON TWP,2016,...,No,No,No,No,No,No,No,No,No,"(40.1764, -74.984)"
1,2016000697,9,Bucks,9224,Upper Makefield Twp,6,District 6-0,09224,UPPER MAKEFIELD TWP,2016,...,No,Yes,No,No,No,No,No,No,No,"(40.3114, -74.9505)"
2,2016001188,36,Lancaster,36408,Ephrata Boro,8,District 8-0,36408,EPHRATA,2016,...,No,Yes,Yes,No,No,No,No,No,No,"(40.1648, -76.2006)"
3,2016001239,64,Westmoreland,64215,Sewickley Twp,12,District 12-0,68A01,PSP - Greensburg,2016,...,Yes,No,No,No,No,No,No,No,No,"(40.2376, -79.7743)"
4,2016001947,23,Delaware,23208,Newtown Twp,6,District 6-0,23208,NEWTOWN TWP,2016,...,No,No,No,No,No,No,No,No,No,"(39.9846, -75.3991)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71670,2017038531,49,Northumberland,49201,Delaware Twp,3,District 3-0,68F06,PSP - Milton,2017,...,Yes,No,No,No,No,No,No,No,No,"(41.1572, -76.8731)"
71671,2017072506,25,Erie,25213,Millcreek Twp,1,District 1-0,25213,MILLCREEK TWP,2017,...,No,Yes,No,No,No,No,No,No,No,"(42.0997, -80.1458)"
71672,2017022897,49,Northumberland,49409,Snydertown Boro,3,District 3-0,68F08,PSP - Stonington,2017,...,No,No,No,No,No,No,No,No,No,"(40.8816, -76.6665)"
71673,2017092445,62,Washington,62228,Union Twp,12,District 12-0,62301,MONONGAHELA CITY,2017,...,Yes,Yes,No,No,Yes,No,No,Yes,Yes,"(40.231, -79.9727)"
71674,2017098202,6,Berks,6214,Exeter Twp,5,District 5-0,06214,EXETER TWP,2017,...,No,Yes,No,No,No,No,No,No,No,"(40.3246, -75.85)"

In [17]:
df.columns

Index(['Crash Record Number', 'County Code', 'County Name',
       'Municipality Code', 'Municipality Name', 'District Code',
       'District Name', 'Police Agency Code', 'Police Agency Name',
       'Crash Year',
       ...
       'Suspected Serious Injury', 'Suspected Minor Injury', 'Possible Injury',
       'Motorcycle Drinking Driver', 'Drug Related', 'Illegal Drug Related',
       'School Bus Unit', 'Drugged Driver', 'Impaired Driver',
       'Geographic Location of the Crash'],
      dtype='object', length=180)

In [18]:
for column in df.columns:
    print(column)

Crash Record Number
County Code
County Name
Municipality Code
Municipality Name
District Code
District Name
Police Agency Code
Police Agency Name
Crash Year
Crash Month
Day of Week
Time of Day
Hour of Day
Illumination
Weather
Road Condition
Collision Type
Work Zone Type
Work Zone Location
Intersection Type
Traffic Control Device
Location Type
Urban / Rural
Fatality Count
Injury Count
Person Count
Total Unit Count
School Bus Indicator
School Zone Indicator
Latitude
Longitude
Arrival Time
Dispatch Time
Construction Zone Speed Limit
Estimated Hours Closed
Lane Closed
Lane Closure Direction
Notify Highway Maintenance
Special Jurisdiction
Traffic Control Device Function
Traffic Detour
Workers Present
Work Zone Close/Detour
Work Zone Flagger
Work Zone Law Officer
Work Zone Closure
Work Zone Moving
Work Zone Other
Work Zone Shoulder/Median
Vehicle Count
Automobile Count
Motorcycle Count
Bus Count
Small Truck Count
Heavy Truck Count
SUV Count
Van Count
Bicycle Count
Suspected Serious Injury Count
Suspected Minor Injury Count
Possible Injury Count
Total Injury Count
Unknown Injury Degree Count
Unknown Injury Person Count
16 Year Old Driver Count
17 Year Old Driver Count
18 Year Old Driver Count
19 Year Old Driver Count
20 Year Old Driver Count
50-64 Year Old Driver Count
65-74 Year Old Driver Count
75 Plus Year Old Driver Count
Unbelted Occupant Count
Unbelted Death Count
Unbelted Suspected Serious Injury Count
Belted Death Count
Belted Suspected Serious Injury Count
Motorcycle Death Count
Motorcycle Suspected Serious Injury Count
Bicycle Death Count
Bicycle Suspected Serious Injury Count
Pedestrian Count
Pedestrian Death Count
Pedestrian Suspected Serious Injury Count
Maximum Severity Level
Commercial Vehicle Count
Latitude (Decimal)
Longitude (Decimal)
Roadway Surface Type
Interstate
State Road
Local Road Only
Turnpike
Wet Road
Snow Slush Road
Icy Road
Sudden Deer
Shoulder Related
Rear End
Head On / Opposite Direction Side Swipe
Hit Fixed Object
Single Vehicle Run Off Road
Work Zone
Property Damage Only
Injury or Fatal
Fatal or Suspected Serious Injury
Injury
Fatal
Non Intersection
Intersection
Signalized Intersection
Stop Controlled Intersection
Unsignalized Intersection
School Bus
School Zone
Hit Deer
Hit Tree / Shrub
Hit Embankment
Hit Pole
Hit Guide Rail
Hit Guide Rail End
Hit Barrier
Hit Bridge
Overturned
Motorcycle
Bicycle
Heavy Truck Related
Vehicle Failure
Train / Trolley
Phantom Vehicle
Alcohol Related
Drinking Driver
Underage Drinking Driver
Unlicensed
Distracted
Cell Phone
No Clearance
Running Red Light
Tailgating
Cross Median
Curved Road
Curve Driver Error
Limit 65 MPH
Speeding
Speeding Related
Aggressive Driving
Fatigue / Asleep
Driver 16 Years Old
Driver 17 Years Old
Driver 18 Years Old
Driver 19 Years Old
Driver 20 Years Old
Driver 50 - 64 Years Old
Driver 65 - 74 Years Old
Driver 75 Plus
Unbelted
Pedestrian
Commercial Vehicle
PSP Reported
NHTSA Aggressive Driving
Deer Related
Illumination Dark
Running Stop Sign
Train
Trolley
Hit Parked Vehicle
Fire In Vehicle
Vehicle Towed
Hazardous Truck
Suspected Serious Injury
Suspected Minor Injury
Possible Injury
Motorcycle Drinking Driver
Drug Related
Illegal Drug Related
School Bus Unit
Drugged Driver
Impaired Driver
Geographic Location of the Crash

In [22]:
vehicle_type = df[['Automobile Count',
'Bus Count',
'Small Truck Count',
'Heavy Truck Count',
'SUV Count',
'Van Count',
'Bicycle Count']]

In [23]:
vehicle_type

,Automobile Count,Bus Count,Small Truck Count,Heavy Truck Count,SUV Count,Van Count,Bicycle Count
0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0
3,0,0,0,0,1,0,0
4,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...
71670,0,0,0,0,0,0,0
71671,0,0,0,0,0,0,0
71672,0,0,0,0,0,0,0
71673,0,0,2,0,0,0,0
71674,1,0,0,0,0,0,0

In [24]:
vehicle_type[vehicle_type > 0] = 1

/home/michaelpfredericks/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/home/michaelpfredericks/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:2986: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._where(-key, value, inplace=True)

In [25]:
vehicle_type

,Automobile Count,Bus Count,Small Truck Count,Heavy Truck Count,SUV Count,Van Count,Bicycle Count
0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0
3,0,0,0,0,1,0,0
4,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...
71670,0,0,0,0,0,0,0
71671,0,0,0,0,0,0,0
71672,0,0,0,0,0,0,0
71673,0,0,1,0,0,0,0
71674,1,0,0,0,0,0,0

In [26]:
columns = vehicle_type.columns.tolist()

In [27]:
columns

['Automobile Count',
 'Bus Count',
 'Small Truck Count',
 'Heavy Truck Count',
 'SUV Count',
 'Van Count',
 'Bicycle Count']

In [28]:
vehicle_type.groupby(1, axis=1).count()

ValueError: operands could not be broadcast together with shapes (7,) (71675,0)